-- 부서1
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('001', '부서1', 'M001', NULL, 1, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서2
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('002', '부서2', 'M002', '001', 2, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서3
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('003', '부서3', 'M003', '002', 3, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서4
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('004', '부서4', 'M004', '003', 4, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서5
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('005', '부서5', 'M005', '003', 5, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서6
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('006', '부서6', 'M006', '003', 6, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서7
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('007', '부서7', 'M007', '004', 7, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서8
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('008', '부서8', 'M008', '007', 8, SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서9
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('009', '부서9', 'M009', '008', 9,  SYSDATE, 'admin', SYSDATE, 'admin');

-- 부서10
INSERT INTO DEPT (DEPT_CD, DEPT_NM, MGR_ID, UPPER_DEPT_CD, SORT, UPD_DT, UPD_ID, REG_DT, REG_ID)
VALUES ('010', '부서10', 'M010', '009', 10,  SYSDATE, 'admin', SYSDATE, 'admin');
