-- ADMIN.AUTH_MST definition

CREATE TABLE ADMIN.AUTH_MST
       (	
           GRP_CD VARCHAR2(10)                       NOT NULL
         , GRP_NM VARCHAR2(100) 
         , REG_DT DATE          DEFAULT CURRENT_DATE NOT NULL
         , REG_ID VARCHAR2(20)                       NOT NULL
         , UPD_DT DATE          DEFAULT CURRENT_DATE NOT NULL
         , UPD_ID VARCHAR2(20)                       NOT NULL
	       
	     , CONSTRAINT AUTH_MST_PK PRIMARY KEY (GRP_CD)
       ) ;

COMMENT ON  TABLE ADMIN.AUTH_MST        IS '권한마스터';
COMMENT ON COLUMN ADMIN.AUTH_MST.GRP_CD IS '그룹코드';
COMMENT ON COLUMN ADMIN.AUTH_MST.GRP_NM IS '그룹명';
COMMENT ON COLUMN ADMIN.AUTH_MST.REG_DT IS '등록일시';
COMMENT ON COLUMN ADMIN.AUTH_MST.REG_ID IS '등록자';
COMMENT ON COLUMN ADMIN.AUTH_MST.UPD_DT IS '수정일시';
COMMENT ON COLUMN ADMIN.AUTH_MST.UPD_ID IS '수정자';




-- ADMIN.AUTH_DTL definition

CREATE TABLE "ADMIN"."AUTH_DTL" 
       (	
           "GRP_CD"   VARCHAR2(10)                      NOT NULL
         , "MENU_CD"  VARCHAR2(10)                      NOT NULL
	     , "USE_YN"   VARCHAR2(1) 
	     , "CRT_YN"   VARCHAR2(1) 
	     , "RED_YN"   VARCHAR2(1) 
	     , "SAV_YN"   VARCHAR2(1) 
	     , "DEL_YN"   VARCHAR2(1) 
	     , "PRT_YN"   VARCHAR2(1) 
	     , "EXL_YN"   VARCHAR2(1) 
	     , "ETC_1_YN" VARCHAR2(1) 
	     , "ETC_2_YN" VARCHAR2(1) 
	     , "ETC_3_YN" VARCHAR2(1) 
	     , "REG_DT"   DATE         DEFAULT CURRENT_DATE NOT NULL
	     , "REG_ID"   VARCHAR2(20)                      NOT NULL
	     , "UPD_DT"   DATE         DEFAULT CURRENT_DATE NOT NULL
	     , "UPD_ID"   VARCHAR2(20)                      NOT NULL
	       
	     , CONSTRAINT "AUTH_DTL_PK"          PRIMARY KEY ("GRP_CD", "MENU_CD")
         , CONSTRAINT "AUTH_DTL_AUTH_MST_FK" FOREIGN KEY ("GRP_CD")
	       REFERENCES "ADMIN"."AUTH_MST"                 ("GRP_CD")
	     , CONSTRAINT "AUTH_DTL_MENU_FK"     FOREIGN KEY ("MENU_CD")
	       REFERENCES "ADMIN"."MENU"                     ("MENU_CD")
       ) ;

COMMENT ON  TABLE ADMIN.AUTH_DTL          IS '권한디테일';
COMMENT ON COLUMN ADMIN.AUTH_DTL.GRP_CD   IS '그룹코드';
COMMENT ON COLUMN ADMIN.AUTH_DTL.MENU_CD  IS '메뉴ID';
COMMENT ON COLUMN ADMIN.AUTH_DTL.USE_YN   IS '표시여부';
COMMENT ON COLUMN ADMIN.AUTH_DTL.CRT_YN   IS '생성권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.RED_YN   IS '읽기권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.SAV_YN   IS '저장권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.DEL_YN   IS '삭제권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.PRT_YN   IS '인쇄권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.EXL_YN   IS '엑셀권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.ETC_1_YN IS '기타1권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.ETC_2_YN IS '기타2권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.ETC_3_YN IS '기타3권한';
COMMENT ON COLUMN ADMIN.AUTH_DTL.REG_DT   IS '등록일시';
COMMENT ON COLUMN ADMIN.AUTH_DTL.REG_ID   IS '등록자';
COMMENT ON COLUMN ADMIN.AUTH_DTL.UPD_DT   IS '수정일시';
COMMENT ON COLUMN ADMIN.AUTH_DTL.UPD_ID   IS '수정자';
